### ISSUE TITLE
mhn install fails on linux ubuntu 18.04

### ISSUE THREAD

**Issue by Xaltmasn** [omererdem/honeything#6]
I am trying to install mhn(modern honey network) on a fresh install of ubuntu 18.04

I got these errors.

Initializing` database, please be patient. This can take several minutes
+ python initdatabase.py
Traceback (most recent call last):
  File "initdatabase.py", line 5, in <module>
    create_clean_db()
  File "/opt/mhn/server/mhn/__init__.py", line 116, in create_clean_db
    db.create_all()
  File "/opt/mhn/env/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 963, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/opt/mhn/env/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 955, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/opt/mhn/env/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 896, in get_engine
    return connector.get_engine()
  File "/opt/mhn/env/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 556, in get_engine
    self._sa.apply_driver_hacks(self._app, info, options)
  File "/opt/mhn/env/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 861, in apply_driver_hacks
    info.database = os.path.join(app.root_path, info.database)
AttributeError: can't set attribute```

how to fix this?

**Comment by mzfr** [comment]
@Xaltmasn This project isn't under development. If you look at it the last commit was done in 2016. Python2.7 is discontinued.
